### ISSUE TITLE
Input fields in MOD calculator

### ISSUE THREAD

**Issue by ashu12chi** [ContriHUB/Upyogaarth#23]
In all 4 screens of the MOD Calculator make the input fields designed according to material designed guidelines (https://material.io).

**Comment by nisiddharth** [comment]
Hey Urvashi, sorry for the late response.

Saw your work, the text fields look nice.

Two suggestions for the future:
1. Make the colours not hardcoded but define them somewhere and then use them.
2. This will also help make the colours dark theme compatible by defining them with the same name separately for the two themes.

[You can refer to [this project's](https://github.com/nisiddharth/BrighterBee/) main.dart to see how we can define colours in light and dark conditions.]

For now, I am merging your PR but I'll be changing the colours to `Colors.grey` for the sake of visibility in both light and dark themes :100:
